version: '3.8'

services:
  app-dev:
    image: ghcr.io/letsgettechnical/dev:latest
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development

  app-github-dev:
    image: ghcr.io/clue355/github_dev:dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

